// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: agent.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "agent.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace comm {

namespace {

const ::google::protobuf::Descriptor* Command_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Command_reflection_ = NULL;
const ::google::protobuf::Descriptor* Command_Vector_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Command_Vector_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_agent_2eproto() {
  protobuf_AddDesc_agent_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "agent.proto");
  GOOGLE_CHECK(file != NULL);
  Command_descriptor_ = file->message_type(0);
  static const int Command_offsets_[13] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, priority_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, travel_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, heading_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, minradius_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, minradiusvalue_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, gravity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, gravitylocation_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, gravitystrength_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, gravitysigma_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, resetgravity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, userforce_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, forcevector_),
  };
  Command_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Command_descriptor_,
      Command::default_instance_,
      Command_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Command));
  Command_Vector_descriptor_ = Command_descriptor_->nested_type(0);
  static const int Command_Vector_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command_Vector, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command_Vector, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command_Vector, z_),
  };
  Command_Vector_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Command_Vector_descriptor_,
      Command_Vector::default_instance_,
      Command_Vector_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command_Vector, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Command_Vector, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Command_Vector));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_agent_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Command_descriptor_, &Command::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Command_Vector_descriptor_, &Command_Vector::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_agent_2eproto() {
  delete Command::default_instance_;
  delete Command_reflection_;
  delete Command_Vector::default_instance_;
  delete Command_Vector_reflection_;
}

void protobuf_AddDesc_agent_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013agent.proto\022\004comm\"\367\002\n\007Command\022\020\n\010prior"
    "ity\030\001 \002(\005\022\n\n\002id\030\002 \002(\005\022\016\n\006travel\030\003 \001(\010\022%\n"
    "\007heading\030\004 \001(\0132\024.comm.Command.Vector\022\021\n\t"
    "minRadius\030\005 \001(\010\022\026\n\016minRadiusValue\030\006 \001(\001\022"
    "\017\n\007gravity\030\007 \001(\010\022-\n\017gravityLocation\030\010 \001("
    "\0132\024.comm.Command.Vector\022\027\n\017gravityStreng"
    "th\030\t \001(\001\022\024\n\014gravitySigma\030\n \001(\001\022\024\n\014resetG"
    "ravity\030\013 \001(\010\022\021\n\tuserForce\030\014 \001(\010\022)\n\013force"
    "Vector\030\r \001(\0132\024.comm.Command.Vector\032)\n\006Ve"
    "ctor\022\t\n\001X\030\001 \002(\001\022\t\n\001Y\030\002 \002(\001\022\t\n\001Z\030\003 \002(\001", 397);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "agent.proto", &protobuf_RegisterTypes);
  Command::default_instance_ = new Command();
  Command_Vector::default_instance_ = new Command_Vector();
  Command::default_instance_->InitAsDefaultInstance();
  Command_Vector::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_agent_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_agent_2eproto {
  StaticDescriptorInitializer_agent_2eproto() {
    protobuf_AddDesc_agent_2eproto();
  }
} static_descriptor_initializer_agent_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Command_Vector::kXFieldNumber;
const int Command_Vector::kYFieldNumber;
const int Command_Vector::kZFieldNumber;
#endif  // !_MSC_VER

Command_Vector::Command_Vector()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:comm.Command.Vector)
}

void Command_Vector::InitAsDefaultInstance() {
}

Command_Vector::Command_Vector(const Command_Vector& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:comm.Command.Vector)
}

void Command_Vector::SharedCtor() {
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
  z_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Command_Vector::~Command_Vector() {
  // @@protoc_insertion_point(destructor:comm.Command.Vector)
  SharedDtor();
}

void Command_Vector::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Command_Vector::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Command_Vector::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Command_Vector_descriptor_;
}

const Command_Vector& Command_Vector::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_agent_2eproto();
  return *default_instance_;
}

Command_Vector* Command_Vector::default_instance_ = NULL;

Command_Vector* Command_Vector::New() const {
  return new Command_Vector;
}

void Command_Vector::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Command_Vector*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(x_, z_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Command_Vector::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:comm.Command.Vector)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required double X = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_Y;
        break;
      }

      // required double Y = 2;
      case 2: {
        if (tag == 17) {
         parse_Y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_Z;
        break;
      }

      // required double Z = 3;
      case 3: {
        if (tag == 25) {
         parse_Z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &z_)));
          set_has_z();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:comm.Command.Vector)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:comm.Command.Vector)
  return false;
#undef DO_
}

void Command_Vector::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:comm.Command.Vector)
  // required double X = 1;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->x(), output);
  }

  // required double Y = 2;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->y(), output);
  }

  // required double Z = 3;
  if (has_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->z(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:comm.Command.Vector)
}

::google::protobuf::uint8* Command_Vector::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:comm.Command.Vector)
  // required double X = 1;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->x(), target);
  }

  // required double Y = 2;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->y(), target);
  }

  // required double Z = 3;
  if (has_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->z(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:comm.Command.Vector)
  return target;
}

int Command_Vector::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required double X = 1;
    if (has_x()) {
      total_size += 1 + 8;
    }

    // required double Y = 2;
    if (has_y()) {
      total_size += 1 + 8;
    }

    // required double Z = 3;
    if (has_z()) {
      total_size += 1 + 8;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Command_Vector::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Command_Vector* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Command_Vector*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Command_Vector::MergeFrom(const Command_Vector& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_z()) {
      set_z(from.z());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Command_Vector::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Command_Vector::CopyFrom(const Command_Vector& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Command_Vector::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void Command_Vector::Swap(Command_Vector* other) {
  if (other != this) {
    std::swap(x_, other->x_);
    std::swap(y_, other->y_);
    std::swap(z_, other->z_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Command_Vector::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Command_Vector_descriptor_;
  metadata.reflection = Command_Vector_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Command::kPriorityFieldNumber;
const int Command::kIdFieldNumber;
const int Command::kTravelFieldNumber;
const int Command::kHeadingFieldNumber;
const int Command::kMinRadiusFieldNumber;
const int Command::kMinRadiusValueFieldNumber;
const int Command::kGravityFieldNumber;
const int Command::kGravityLocationFieldNumber;
const int Command::kGravityStrengthFieldNumber;
const int Command::kGravitySigmaFieldNumber;
const int Command::kResetGravityFieldNumber;
const int Command::kUserForceFieldNumber;
const int Command::kForceVectorFieldNumber;
#endif  // !_MSC_VER

Command::Command()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:comm.Command)
}

void Command::InitAsDefaultInstance() {
  heading_ = const_cast< ::comm::Command_Vector*>(&::comm::Command_Vector::default_instance());
  gravitylocation_ = const_cast< ::comm::Command_Vector*>(&::comm::Command_Vector::default_instance());
  forcevector_ = const_cast< ::comm::Command_Vector*>(&::comm::Command_Vector::default_instance());
}

Command::Command(const Command& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:comm.Command)
}

void Command::SharedCtor() {
  _cached_size_ = 0;
  priority_ = 0;
  id_ = 0;
  travel_ = false;
  heading_ = NULL;
  minradius_ = false;
  minradiusvalue_ = 0;
  gravity_ = false;
  gravitylocation_ = NULL;
  gravitystrength_ = 0;
  gravitysigma_ = 0;
  resetgravity_ = false;
  userforce_ = false;
  forcevector_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Command::~Command() {
  // @@protoc_insertion_point(destructor:comm.Command)
  SharedDtor();
}

void Command::SharedDtor() {
  if (this != default_instance_) {
    delete heading_;
    delete gravitylocation_;
    delete forcevector_;
  }
}

void Command::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Command::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Command_descriptor_;
}

const Command& Command::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_agent_2eproto();
  return *default_instance_;
}

Command* Command::default_instance_ = NULL;

Command* Command::New() const {
  return new Command;
}

void Command::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Command*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 255) {
    ZR_(priority_, id_);
    ZR_(minradiusvalue_, gravity_);
    if (has_heading()) {
      if (heading_ != NULL) heading_->::comm::Command_Vector::Clear();
    }
    if (has_gravitylocation()) {
      if (gravitylocation_ != NULL) gravitylocation_->::comm::Command_Vector::Clear();
    }
  }
  if (_has_bits_[8 / 32] & 7936) {
    ZR_(resetgravity_, userforce_);
    ZR_(gravitystrength_, gravitysigma_);
    if (has_forcevector()) {
      if (forcevector_ != NULL) forcevector_->::comm::Command_Vector::Clear();
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Command::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:comm.Command)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 priority = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &priority_)));
          set_has_priority();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_id;
        break;
      }

      // required int32 id = 2;
      case 2: {
        if (tag == 16) {
         parse_id:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_travel;
        break;
      }

      // optional bool travel = 3;
      case 3: {
        if (tag == 24) {
         parse_travel:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &travel_)));
          set_has_travel();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_heading;
        break;
      }

      // optional .comm.Command.Vector heading = 4;
      case 4: {
        if (tag == 34) {
         parse_heading:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_heading()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_minRadius;
        break;
      }

      // optional bool minRadius = 5;
      case 5: {
        if (tag == 40) {
         parse_minRadius:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &minradius_)));
          set_has_minradius();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(49)) goto parse_minRadiusValue;
        break;
      }

      // optional double minRadiusValue = 6;
      case 6: {
        if (tag == 49) {
         parse_minRadiusValue:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &minradiusvalue_)));
          set_has_minradiusvalue();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_gravity;
        break;
      }

      // optional bool gravity = 7;
      case 7: {
        if (tag == 56) {
         parse_gravity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &gravity_)));
          set_has_gravity();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_gravityLocation;
        break;
      }

      // optional .comm.Command.Vector gravityLocation = 8;
      case 8: {
        if (tag == 66) {
         parse_gravityLocation:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_gravitylocation()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(73)) goto parse_gravityStrength;
        break;
      }

      // optional double gravityStrength = 9;
      case 9: {
        if (tag == 73) {
         parse_gravityStrength:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &gravitystrength_)));
          set_has_gravitystrength();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(81)) goto parse_gravitySigma;
        break;
      }

      // optional double gravitySigma = 10;
      case 10: {
        if (tag == 81) {
         parse_gravitySigma:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &gravitysigma_)));
          set_has_gravitysigma();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(88)) goto parse_resetGravity;
        break;
      }

      // optional bool resetGravity = 11;
      case 11: {
        if (tag == 88) {
         parse_resetGravity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &resetgravity_)));
          set_has_resetgravity();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(96)) goto parse_userForce;
        break;
      }

      // optional bool userForce = 12;
      case 12: {
        if (tag == 96) {
         parse_userForce:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &userforce_)));
          set_has_userforce();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(106)) goto parse_forceVector;
        break;
      }

      // optional .comm.Command.Vector forceVector = 13;
      case 13: {
        if (tag == 106) {
         parse_forceVector:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_forcevector()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:comm.Command)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:comm.Command)
  return false;
#undef DO_
}

void Command::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:comm.Command)
  // required int32 priority = 1;
  if (has_priority()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->priority(), output);
  }

  // required int32 id = 2;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->id(), output);
  }

  // optional bool travel = 3;
  if (has_travel()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->travel(), output);
  }

  // optional .comm.Command.Vector heading = 4;
  if (has_heading()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->heading(), output);
  }

  // optional bool minRadius = 5;
  if (has_minradius()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->minradius(), output);
  }

  // optional double minRadiusValue = 6;
  if (has_minradiusvalue()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(6, this->minradiusvalue(), output);
  }

  // optional bool gravity = 7;
  if (has_gravity()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->gravity(), output);
  }

  // optional .comm.Command.Vector gravityLocation = 8;
  if (has_gravitylocation()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      8, this->gravitylocation(), output);
  }

  // optional double gravityStrength = 9;
  if (has_gravitystrength()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->gravitystrength(), output);
  }

  // optional double gravitySigma = 10;
  if (has_gravitysigma()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->gravitysigma(), output);
  }

  // optional bool resetGravity = 11;
  if (has_resetgravity()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(11, this->resetgravity(), output);
  }

  // optional bool userForce = 12;
  if (has_userforce()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(12, this->userforce(), output);
  }

  // optional .comm.Command.Vector forceVector = 13;
  if (has_forcevector()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      13, this->forcevector(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:comm.Command)
}

::google::protobuf::uint8* Command::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:comm.Command)
  // required int32 priority = 1;
  if (has_priority()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->priority(), target);
  }

  // required int32 id = 2;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->id(), target);
  }

  // optional bool travel = 3;
  if (has_travel()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->travel(), target);
  }

  // optional .comm.Command.Vector heading = 4;
  if (has_heading()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->heading(), target);
  }

  // optional bool minRadius = 5;
  if (has_minradius()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(5, this->minradius(), target);
  }

  // optional double minRadiusValue = 6;
  if (has_minradiusvalue()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(6, this->minradiusvalue(), target);
  }

  // optional bool gravity = 7;
  if (has_gravity()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(7, this->gravity(), target);
  }

  // optional .comm.Command.Vector gravityLocation = 8;
  if (has_gravitylocation()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        8, this->gravitylocation(), target);
  }

  // optional double gravityStrength = 9;
  if (has_gravitystrength()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->gravitystrength(), target);
  }

  // optional double gravitySigma = 10;
  if (has_gravitysigma()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->gravitysigma(), target);
  }

  // optional bool resetGravity = 11;
  if (has_resetgravity()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(11, this->resetgravity(), target);
  }

  // optional bool userForce = 12;
  if (has_userforce()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(12, this->userforce(), target);
  }

  // optional .comm.Command.Vector forceVector = 13;
  if (has_forcevector()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        13, this->forcevector(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:comm.Command)
  return target;
}

int Command::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 priority = 1;
    if (has_priority()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->priority());
    }

    // required int32 id = 2;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // optional bool travel = 3;
    if (has_travel()) {
      total_size += 1 + 1;
    }

    // optional .comm.Command.Vector heading = 4;
    if (has_heading()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->heading());
    }

    // optional bool minRadius = 5;
    if (has_minradius()) {
      total_size += 1 + 1;
    }

    // optional double minRadiusValue = 6;
    if (has_minradiusvalue()) {
      total_size += 1 + 8;
    }

    // optional bool gravity = 7;
    if (has_gravity()) {
      total_size += 1 + 1;
    }

    // optional .comm.Command.Vector gravityLocation = 8;
    if (has_gravitylocation()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->gravitylocation());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional double gravityStrength = 9;
    if (has_gravitystrength()) {
      total_size += 1 + 8;
    }

    // optional double gravitySigma = 10;
    if (has_gravitysigma()) {
      total_size += 1 + 8;
    }

    // optional bool resetGravity = 11;
    if (has_resetgravity()) {
      total_size += 1 + 1;
    }

    // optional bool userForce = 12;
    if (has_userforce()) {
      total_size += 1 + 1;
    }

    // optional .comm.Command.Vector forceVector = 13;
    if (has_forcevector()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->forcevector());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Command::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Command* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Command*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Command::MergeFrom(const Command& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_priority()) {
      set_priority(from.priority());
    }
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_travel()) {
      set_travel(from.travel());
    }
    if (from.has_heading()) {
      mutable_heading()->::comm::Command_Vector::MergeFrom(from.heading());
    }
    if (from.has_minradius()) {
      set_minradius(from.minradius());
    }
    if (from.has_minradiusvalue()) {
      set_minradiusvalue(from.minradiusvalue());
    }
    if (from.has_gravity()) {
      set_gravity(from.gravity());
    }
    if (from.has_gravitylocation()) {
      mutable_gravitylocation()->::comm::Command_Vector::MergeFrom(from.gravitylocation());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_gravitystrength()) {
      set_gravitystrength(from.gravitystrength());
    }
    if (from.has_gravitysigma()) {
      set_gravitysigma(from.gravitysigma());
    }
    if (from.has_resetgravity()) {
      set_resetgravity(from.resetgravity());
    }
    if (from.has_userforce()) {
      set_userforce(from.userforce());
    }
    if (from.has_forcevector()) {
      mutable_forcevector()->::comm::Command_Vector::MergeFrom(from.forcevector());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Command::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Command::CopyFrom(const Command& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Command::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_heading()) {
    if (!this->heading().IsInitialized()) return false;
  }
  if (has_gravitylocation()) {
    if (!this->gravitylocation().IsInitialized()) return false;
  }
  if (has_forcevector()) {
    if (!this->forcevector().IsInitialized()) return false;
  }
  return true;
}

void Command::Swap(Command* other) {
  if (other != this) {
    std::swap(priority_, other->priority_);
    std::swap(id_, other->id_);
    std::swap(travel_, other->travel_);
    std::swap(heading_, other->heading_);
    std::swap(minradius_, other->minradius_);
    std::swap(minradiusvalue_, other->minradiusvalue_);
    std::swap(gravity_, other->gravity_);
    std::swap(gravitylocation_, other->gravitylocation_);
    std::swap(gravitystrength_, other->gravitystrength_);
    std::swap(gravitysigma_, other->gravitysigma_);
    std::swap(resetgravity_, other->resetgravity_);
    std::swap(userforce_, other->userforce_);
    std::swap(forcevector_, other->forcevector_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Command::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Command_descriptor_;
  metadata.reflection = Command_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm

// @@protoc_insertion_point(global_scope)
