// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: command.proto

#ifndef PROTOBUF_command_2eproto__INCLUDED
#define PROTOBUF_command_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace comm {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_command_2eproto();
void protobuf_AssignDesc_command_2eproto();
void protobuf_ShutdownFile_command_2eproto();

class Query;
class SimCommand;
class FPS;

enum Query_Type {
  Query_Type_SWARM = 0,
  Query_Type_POLYGONS = 1,
  Query_Type_GRAVITY = 2
};
bool Query_Type_IsValid(int value);
const Query_Type Query_Type_Type_MIN = Query_Type_SWARM;
const Query_Type Query_Type_Type_MAX = Query_Type_GRAVITY;
const int Query_Type_Type_ARRAYSIZE = Query_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* Query_Type_descriptor();
inline const ::std::string& Query_Type_Name(Query_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    Query_Type_descriptor(), value);
}
inline bool Query_Type_Parse(
    const ::std::string& name, Query_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Query_Type>(
    Query_Type_descriptor(), name, value);
}
enum SimCommand_Type {
  SimCommand_Type_PAUSE = 1,
  SimCommand_Type_UNPAUSE = 2,
  SimCommand_Type_QUIT = 3,
  SimCommand_Type_FPS = 4
};
bool SimCommand_Type_IsValid(int value);
const SimCommand_Type SimCommand_Type_Type_MIN = SimCommand_Type_PAUSE;
const SimCommand_Type SimCommand_Type_Type_MAX = SimCommand_Type_FPS;
const int SimCommand_Type_Type_ARRAYSIZE = SimCommand_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* SimCommand_Type_descriptor();
inline const ::std::string& SimCommand_Type_Name(SimCommand_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    SimCommand_Type_descriptor(), value);
}
inline bool SimCommand_Type_Parse(
    const ::std::string& name, SimCommand_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SimCommand_Type>(
    SimCommand_Type_descriptor(), name, value);
}
// ===================================================================

class Query : public ::google::protobuf::Message {
 public:
  Query();
  virtual ~Query();

  Query(const Query& from);

  inline Query& operator=(const Query& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Query& default_instance();

  void Swap(Query* other);

  // implements Message ----------------------------------------------

  Query* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Query& from);
  void MergeFrom(const Query& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Query_Type Type;
  static const Type SWARM = Query_Type_SWARM;
  static const Type POLYGONS = Query_Type_POLYGONS;
  static const Type GRAVITY = Query_Type_GRAVITY;
  static inline bool Type_IsValid(int value) {
    return Query_Type_IsValid(value);
  }
  static const Type Type_MIN =
    Query_Type_Type_MIN;
  static const Type Type_MAX =
    Query_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    Query_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return Query_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return Query_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return Query_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .comm.Query.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::comm::Query_Type type() const;
  inline void set_type(::comm::Query_Type value);

  // @@protoc_insertion_point(class_scope:comm.Query)
 private:
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int type_;
  friend void  protobuf_AddDesc_command_2eproto();
  friend void protobuf_AssignDesc_command_2eproto();
  friend void protobuf_ShutdownFile_command_2eproto();

  void InitAsDefaultInstance();
  static Query* default_instance_;
};
// -------------------------------------------------------------------

class SimCommand : public ::google::protobuf::Message {
 public:
  SimCommand();
  virtual ~SimCommand();

  SimCommand(const SimCommand& from);

  inline SimCommand& operator=(const SimCommand& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SimCommand& default_instance();

  void Swap(SimCommand* other);

  // implements Message ----------------------------------------------

  SimCommand* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SimCommand& from);
  void MergeFrom(const SimCommand& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef SimCommand_Type Type;
  static const Type PAUSE = SimCommand_Type_PAUSE;
  static const Type UNPAUSE = SimCommand_Type_UNPAUSE;
  static const Type QUIT = SimCommand_Type_QUIT;
  static const Type FPS = SimCommand_Type_FPS;
  static inline bool Type_IsValid(int value) {
    return SimCommand_Type_IsValid(value);
  }
  static const Type Type_MIN =
    SimCommand_Type_Type_MIN;
  static const Type Type_MAX =
    SimCommand_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    SimCommand_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return SimCommand_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return SimCommand_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return SimCommand_Type_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .comm.SimCommand.Type type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::comm::SimCommand_Type type() const;
  inline void set_type(::comm::SimCommand_Type value);

  // @@protoc_insertion_point(class_scope:comm.SimCommand)
 private:
  inline void set_has_type();
  inline void clear_has_type();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  int type_;
  friend void  protobuf_AddDesc_command_2eproto();
  friend void protobuf_AssignDesc_command_2eproto();
  friend void protobuf_ShutdownFile_command_2eproto();

  void InitAsDefaultInstance();
  static SimCommand* default_instance_;
};
// -------------------------------------------------------------------

class FPS : public ::google::protobuf::Message {
 public:
  FPS();
  virtual ~FPS();

  FPS(const FPS& from);

  inline FPS& operator=(const FPS& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const FPS& default_instance();

  void Swap(FPS* other);

  // implements Message ----------------------------------------------

  FPS* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const FPS& from);
  void MergeFrom(const FPS& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double frames = 1;
  inline bool has_frames() const;
  inline void clear_frames();
  static const int kFramesFieldNumber = 1;
  inline double frames() const;
  inline void set_frames(double value);

  // @@protoc_insertion_point(class_scope:comm.FPS)
 private:
  inline void set_has_frames();
  inline void clear_has_frames();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double frames_;
  friend void  protobuf_AddDesc_command_2eproto();
  friend void protobuf_AssignDesc_command_2eproto();
  friend void protobuf_ShutdownFile_command_2eproto();

  void InitAsDefaultInstance();
  static FPS* default_instance_;
};
// ===================================================================


// ===================================================================

// Query

// required .comm.Query.Type type = 1;
inline bool Query::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Query::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Query::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Query::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::comm::Query_Type Query::type() const {
  // @@protoc_insertion_point(field_get:comm.Query.type)
  return static_cast< ::comm::Query_Type >(type_);
}
inline void Query::set_type(::comm::Query_Type value) {
  assert(::comm::Query_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:comm.Query.type)
}

// -------------------------------------------------------------------

// SimCommand

// required .comm.SimCommand.Type type = 1;
inline bool SimCommand::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SimCommand::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SimCommand::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SimCommand::clear_type() {
  type_ = 1;
  clear_has_type();
}
inline ::comm::SimCommand_Type SimCommand::type() const {
  // @@protoc_insertion_point(field_get:comm.SimCommand.type)
  return static_cast< ::comm::SimCommand_Type >(type_);
}
inline void SimCommand::set_type(::comm::SimCommand_Type value) {
  assert(::comm::SimCommand_Type_IsValid(value));
  set_has_type();
  type_ = value;
  // @@protoc_insertion_point(field_set:comm.SimCommand.type)
}

// -------------------------------------------------------------------

// FPS

// required double frames = 1;
inline bool FPS::has_frames() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void FPS::set_has_frames() {
  _has_bits_[0] |= 0x00000001u;
}
inline void FPS::clear_has_frames() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void FPS::clear_frames() {
  frames_ = 0;
  clear_has_frames();
}
inline double FPS::frames() const {
  // @@protoc_insertion_point(field_get:comm.FPS.frames)
  return frames_;
}
inline void FPS::set_frames(double value) {
  set_has_frames();
  frames_ = value;
  // @@protoc_insertion_point(field_set:comm.FPS.frames)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::comm::Query_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::comm::Query_Type>() {
  return ::comm::Query_Type_descriptor();
}
template <> struct is_proto_enum< ::comm::SimCommand_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::comm::SimCommand_Type>() {
  return ::comm::SimCommand_Type_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_command_2eproto__INCLUDED
