// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gravity.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "gravity.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace comm {

namespace {

const ::google::protobuf::Descriptor* GravityList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GravityList_reflection_ = NULL;
const ::google::protobuf::Descriptor* GravityList_GravityWell_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  GravityList_GravityWell_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_gravity_2eproto() {
  protobuf_AddDesc_gravity_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "gravity.proto");
  GOOGLE_CHECK(file != NULL);
  GravityList_descriptor_ = file->message_type(0);
  static const int GravityList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GravityList, wells_),
  };
  GravityList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GravityList_descriptor_,
      GravityList::default_instance_,
      GravityList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GravityList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GravityList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GravityList));
  GravityList_GravityWell_descriptor_ = GravityList_descriptor_->nested_type(0);
  static const int GravityList_GravityWell_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GravityList_GravityWell, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GravityList_GravityWell, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GravityList_GravityWell, z_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GravityList_GravityWell, sigma_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GravityList_GravityWell, strength_),
  };
  GravityList_GravityWell_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      GravityList_GravityWell_descriptor_,
      GravityList_GravityWell::default_instance_,
      GravityList_GravityWell_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GravityList_GravityWell, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(GravityList_GravityWell, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(GravityList_GravityWell));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_gravity_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GravityList_descriptor_, &GravityList::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    GravityList_GravityWell_descriptor_, &GravityList_GravityWell::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_gravity_2eproto() {
  delete GravityList::default_instance_;
  delete GravityList_reflection_;
  delete GravityList_GravityWell::default_instance_;
  delete GravityList_GravityWell_reflection_;
}

void protobuf_AddDesc_gravity_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rgravity.proto\022\004comm\"\214\001\n\013GravityList\022,\n"
    "\005wells\030\001 \003(\0132\035.comm.GravityList.GravityW"
    "ell\032O\n\013GravityWell\022\t\n\001x\030\001 \002(\001\022\t\n\001y\030\002 \002(\001"
    "\022\t\n\001z\030\003 \002(\001\022\r\n\005sigma\030\004 \002(\001\022\020\n\010strength\030\005"
    " \002(\001", 164);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "gravity.proto", &protobuf_RegisterTypes);
  GravityList::default_instance_ = new GravityList();
  GravityList_GravityWell::default_instance_ = new GravityList_GravityWell();
  GravityList::default_instance_->InitAsDefaultInstance();
  GravityList_GravityWell::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_gravity_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_gravity_2eproto {
  StaticDescriptorInitializer_gravity_2eproto() {
    protobuf_AddDesc_gravity_2eproto();
  }
} static_descriptor_initializer_gravity_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int GravityList_GravityWell::kXFieldNumber;
const int GravityList_GravityWell::kYFieldNumber;
const int GravityList_GravityWell::kZFieldNumber;
const int GravityList_GravityWell::kSigmaFieldNumber;
const int GravityList_GravityWell::kStrengthFieldNumber;
#endif  // !_MSC_VER

GravityList_GravityWell::GravityList_GravityWell()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:comm.GravityList.GravityWell)
}

void GravityList_GravityWell::InitAsDefaultInstance() {
}

GravityList_GravityWell::GravityList_GravityWell(const GravityList_GravityWell& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:comm.GravityList.GravityWell)
}

void GravityList_GravityWell::SharedCtor() {
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
  z_ = 0;
  sigma_ = 0;
  strength_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GravityList_GravityWell::~GravityList_GravityWell() {
  // @@protoc_insertion_point(destructor:comm.GravityList.GravityWell)
  SharedDtor();
}

void GravityList_GravityWell::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GravityList_GravityWell::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GravityList_GravityWell::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GravityList_GravityWell_descriptor_;
}

const GravityList_GravityWell& GravityList_GravityWell::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_gravity_2eproto();
  return *default_instance_;
}

GravityList_GravityWell* GravityList_GravityWell::default_instance_ = NULL;

GravityList_GravityWell* GravityList_GravityWell::New() const {
  return new GravityList_GravityWell;
}

void GravityList_GravityWell::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<GravityList_GravityWell*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 31) {
    ZR_(x_, strength_);
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GravityList_GravityWell::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:comm.GravityList.GravityWell)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required double x = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_y;
        break;
      }

      // required double y = 2;
      case 2: {
        if (tag == 17) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_z;
        break;
      }

      // required double z = 3;
      case 3: {
        if (tag == 25) {
         parse_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &z_)));
          set_has_z();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_sigma;
        break;
      }

      // required double sigma = 4;
      case 4: {
        if (tag == 33) {
         parse_sigma:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &sigma_)));
          set_has_sigma();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(41)) goto parse_strength;
        break;
      }

      // required double strength = 5;
      case 5: {
        if (tag == 41) {
         parse_strength:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &strength_)));
          set_has_strength();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:comm.GravityList.GravityWell)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:comm.GravityList.GravityWell)
  return false;
#undef DO_
}

void GravityList_GravityWell::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:comm.GravityList.GravityWell)
  // required double x = 1;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->x(), output);
  }

  // required double y = 2;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->y(), output);
  }

  // required double z = 3;
  if (has_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->z(), output);
  }

  // required double sigma = 4;
  if (has_sigma()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->sigma(), output);
  }

  // required double strength = 5;
  if (has_strength()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(5, this->strength(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:comm.GravityList.GravityWell)
}

::google::protobuf::uint8* GravityList_GravityWell::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:comm.GravityList.GravityWell)
  // required double x = 1;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->x(), target);
  }

  // required double y = 2;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->y(), target);
  }

  // required double z = 3;
  if (has_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->z(), target);
  }

  // required double sigma = 4;
  if (has_sigma()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->sigma(), target);
  }

  // required double strength = 5;
  if (has_strength()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(5, this->strength(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:comm.GravityList.GravityWell)
  return target;
}

int GravityList_GravityWell::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required double x = 1;
    if (has_x()) {
      total_size += 1 + 8;
    }

    // required double y = 2;
    if (has_y()) {
      total_size += 1 + 8;
    }

    // required double z = 3;
    if (has_z()) {
      total_size += 1 + 8;
    }

    // required double sigma = 4;
    if (has_sigma()) {
      total_size += 1 + 8;
    }

    // required double strength = 5;
    if (has_strength()) {
      total_size += 1 + 8;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GravityList_GravityWell::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GravityList_GravityWell* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GravityList_GravityWell*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GravityList_GravityWell::MergeFrom(const GravityList_GravityWell& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_z()) {
      set_z(from.z());
    }
    if (from.has_sigma()) {
      set_sigma(from.sigma());
    }
    if (from.has_strength()) {
      set_strength(from.strength());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GravityList_GravityWell::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GravityList_GravityWell::CopyFrom(const GravityList_GravityWell& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GravityList_GravityWell::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000001f) != 0x0000001f) return false;

  return true;
}

void GravityList_GravityWell::Swap(GravityList_GravityWell* other) {
  if (other != this) {
    std::swap(x_, other->x_);
    std::swap(y_, other->y_);
    std::swap(z_, other->z_);
    std::swap(sigma_, other->sigma_);
    std::swap(strength_, other->strength_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GravityList_GravityWell::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GravityList_GravityWell_descriptor_;
  metadata.reflection = GravityList_GravityWell_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int GravityList::kWellsFieldNumber;
#endif  // !_MSC_VER

GravityList::GravityList()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:comm.GravityList)
}

void GravityList::InitAsDefaultInstance() {
}

GravityList::GravityList(const GravityList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:comm.GravityList)
}

void GravityList::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

GravityList::~GravityList() {
  // @@protoc_insertion_point(destructor:comm.GravityList)
  SharedDtor();
}

void GravityList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void GravityList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* GravityList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return GravityList_descriptor_;
}

const GravityList& GravityList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_gravity_2eproto();
  return *default_instance_;
}

GravityList* GravityList::default_instance_ = NULL;

GravityList* GravityList::New() const {
  return new GravityList;
}

void GravityList::Clear() {
  wells_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool GravityList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:comm.GravityList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .comm.GravityList.GravityWell wells = 1;
      case 1: {
        if (tag == 10) {
         parse_wells:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_wells()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_wells;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:comm.GravityList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:comm.GravityList)
  return false;
#undef DO_
}

void GravityList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:comm.GravityList)
  // repeated .comm.GravityList.GravityWell wells = 1;
  for (int i = 0; i < this->wells_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->wells(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:comm.GravityList)
}

::google::protobuf::uint8* GravityList::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:comm.GravityList)
  // repeated .comm.GravityList.GravityWell wells = 1;
  for (int i = 0; i < this->wells_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->wells(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:comm.GravityList)
  return target;
}

int GravityList::ByteSize() const {
  int total_size = 0;

  // repeated .comm.GravityList.GravityWell wells = 1;
  total_size += 1 * this->wells_size();
  for (int i = 0; i < this->wells_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->wells(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void GravityList::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const GravityList* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const GravityList*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void GravityList::MergeFrom(const GravityList& from) {
  GOOGLE_CHECK_NE(&from, this);
  wells_.MergeFrom(from.wells_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void GravityList::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GravityList::CopyFrom(const GravityList& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GravityList::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->wells())) return false;
  return true;
}

void GravityList::Swap(GravityList* other) {
  if (other != this) {
    wells_.Swap(&other->wells_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata GravityList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = GravityList_descriptor_;
  metadata.reflection = GravityList_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm

// @@protoc_insertion_point(global_scope)
