// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gravity.proto

#ifndef PROTOBUF_gravity_2eproto__INCLUDED
#define PROTOBUF_gravity_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace comm {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_gravity_2eproto();
void protobuf_AssignDesc_gravity_2eproto();
void protobuf_ShutdownFile_gravity_2eproto();

class GravityList;
class GravityList_GravityWell;

// ===================================================================

class GravityList_GravityWell : public ::google::protobuf::Message {
 public:
  GravityList_GravityWell();
  virtual ~GravityList_GravityWell();

  GravityList_GravityWell(const GravityList_GravityWell& from);

  inline GravityList_GravityWell& operator=(const GravityList_GravityWell& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GravityList_GravityWell& default_instance();

  void Swap(GravityList_GravityWell* other);

  // implements Message ----------------------------------------------

  GravityList_GravityWell* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GravityList_GravityWell& from);
  void MergeFrom(const GravityList_GravityWell& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline double x() const;
  inline void set_x(double value);

  // required double y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline double y() const;
  inline void set_y(double value);

  // required double z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline double z() const;
  inline void set_z(double value);

  // required double sigma = 4;
  inline bool has_sigma() const;
  inline void clear_sigma();
  static const int kSigmaFieldNumber = 4;
  inline double sigma() const;
  inline void set_sigma(double value);

  // required double strength = 5;
  inline bool has_strength() const;
  inline void clear_strength();
  static const int kStrengthFieldNumber = 5;
  inline double strength() const;
  inline void set_strength(double value);

  // @@protoc_insertion_point(class_scope:comm.GravityList.GravityWell)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  inline void set_has_sigma();
  inline void clear_has_sigma();
  inline void set_has_strength();
  inline void clear_has_strength();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  double sigma_;
  double strength_;
  friend void  protobuf_AddDesc_gravity_2eproto();
  friend void protobuf_AssignDesc_gravity_2eproto();
  friend void protobuf_ShutdownFile_gravity_2eproto();

  void InitAsDefaultInstance();
  static GravityList_GravityWell* default_instance_;
};
// -------------------------------------------------------------------

class GravityList : public ::google::protobuf::Message {
 public:
  GravityList();
  virtual ~GravityList();

  GravityList(const GravityList& from);

  inline GravityList& operator=(const GravityList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const GravityList& default_instance();

  void Swap(GravityList* other);

  // implements Message ----------------------------------------------

  GravityList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const GravityList& from);
  void MergeFrom(const GravityList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef GravityList_GravityWell GravityWell;

  // accessors -------------------------------------------------------

  // repeated .comm.GravityList.GravityWell wells = 1;
  inline int wells_size() const;
  inline void clear_wells();
  static const int kWellsFieldNumber = 1;
  inline const ::comm::GravityList_GravityWell& wells(int index) const;
  inline ::comm::GravityList_GravityWell* mutable_wells(int index);
  inline ::comm::GravityList_GravityWell* add_wells();
  inline const ::google::protobuf::RepeatedPtrField< ::comm::GravityList_GravityWell >&
      wells() const;
  inline ::google::protobuf::RepeatedPtrField< ::comm::GravityList_GravityWell >*
      mutable_wells();

  // @@protoc_insertion_point(class_scope:comm.GravityList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::comm::GravityList_GravityWell > wells_;
  friend void  protobuf_AddDesc_gravity_2eproto();
  friend void protobuf_AssignDesc_gravity_2eproto();
  friend void protobuf_ShutdownFile_gravity_2eproto();

  void InitAsDefaultInstance();
  static GravityList* default_instance_;
};
// ===================================================================


// ===================================================================

// GravityList_GravityWell

// required double x = 1;
inline bool GravityList_GravityWell::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void GravityList_GravityWell::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void GravityList_GravityWell::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void GravityList_GravityWell::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double GravityList_GravityWell::x() const {
  // @@protoc_insertion_point(field_get:comm.GravityList.GravityWell.x)
  return x_;
}
inline void GravityList_GravityWell::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:comm.GravityList.GravityWell.x)
}

// required double y = 2;
inline bool GravityList_GravityWell::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void GravityList_GravityWell::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void GravityList_GravityWell::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void GravityList_GravityWell::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double GravityList_GravityWell::y() const {
  // @@protoc_insertion_point(field_get:comm.GravityList.GravityWell.y)
  return y_;
}
inline void GravityList_GravityWell::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:comm.GravityList.GravityWell.y)
}

// required double z = 3;
inline bool GravityList_GravityWell::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void GravityList_GravityWell::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void GravityList_GravityWell::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void GravityList_GravityWell::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double GravityList_GravityWell::z() const {
  // @@protoc_insertion_point(field_get:comm.GravityList.GravityWell.z)
  return z_;
}
inline void GravityList_GravityWell::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:comm.GravityList.GravityWell.z)
}

// required double sigma = 4;
inline bool GravityList_GravityWell::has_sigma() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void GravityList_GravityWell::set_has_sigma() {
  _has_bits_[0] |= 0x00000008u;
}
inline void GravityList_GravityWell::clear_has_sigma() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void GravityList_GravityWell::clear_sigma() {
  sigma_ = 0;
  clear_has_sigma();
}
inline double GravityList_GravityWell::sigma() const {
  // @@protoc_insertion_point(field_get:comm.GravityList.GravityWell.sigma)
  return sigma_;
}
inline void GravityList_GravityWell::set_sigma(double value) {
  set_has_sigma();
  sigma_ = value;
  // @@protoc_insertion_point(field_set:comm.GravityList.GravityWell.sigma)
}

// required double strength = 5;
inline bool GravityList_GravityWell::has_strength() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void GravityList_GravityWell::set_has_strength() {
  _has_bits_[0] |= 0x00000010u;
}
inline void GravityList_GravityWell::clear_has_strength() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void GravityList_GravityWell::clear_strength() {
  strength_ = 0;
  clear_has_strength();
}
inline double GravityList_GravityWell::strength() const {
  // @@protoc_insertion_point(field_get:comm.GravityList.GravityWell.strength)
  return strength_;
}
inline void GravityList_GravityWell::set_strength(double value) {
  set_has_strength();
  strength_ = value;
  // @@protoc_insertion_point(field_set:comm.GravityList.GravityWell.strength)
}

// -------------------------------------------------------------------

// GravityList

// repeated .comm.GravityList.GravityWell wells = 1;
inline int GravityList::wells_size() const {
  return wells_.size();
}
inline void GravityList::clear_wells() {
  wells_.Clear();
}
inline const ::comm::GravityList_GravityWell& GravityList::wells(int index) const {
  // @@protoc_insertion_point(field_get:comm.GravityList.wells)
  return wells_.Get(index);
}
inline ::comm::GravityList_GravityWell* GravityList::mutable_wells(int index) {
  // @@protoc_insertion_point(field_mutable:comm.GravityList.wells)
  return wells_.Mutable(index);
}
inline ::comm::GravityList_GravityWell* GravityList::add_wells() {
  // @@protoc_insertion_point(field_add:comm.GravityList.wells)
  return wells_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::comm::GravityList_GravityWell >&
GravityList::wells() const {
  // @@protoc_insertion_point(field_list:comm.GravityList.wells)
  return wells_;
}
inline ::google::protobuf::RepeatedPtrField< ::comm::GravityList_GravityWell >*
GravityList::mutable_wells() {
  // @@protoc_insertion_point(field_mutable_list:comm.GravityList.wells)
  return &wells_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gravity_2eproto__INCLUDED
