// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: polygon.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "polygon.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace comm {

namespace {

const ::google::protobuf::Descriptor* PolygonList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PolygonList_reflection_ = NULL;
const ::google::protobuf::Descriptor* PolygonList_Polygon_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PolygonList_Polygon_reflection_ = NULL;
const ::google::protobuf::Descriptor* PolygonList_Polygon_Vertex_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PolygonList_Polygon_Vertex_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_polygon_2eproto() {
  protobuf_AddDesc_polygon_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "polygon.proto");
  GOOGLE_CHECK(file != NULL);
  PolygonList_descriptor_ = file->message_type(0);
  static const int PolygonList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolygonList, polygons_),
  };
  PolygonList_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PolygonList_descriptor_,
      PolygonList::default_instance_,
      PolygonList_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolygonList, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolygonList, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PolygonList));
  PolygonList_Polygon_descriptor_ = PolygonList_descriptor_->nested_type(0);
  static const int PolygonList_Polygon_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolygonList_Polygon, vertices_),
  };
  PolygonList_Polygon_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PolygonList_Polygon_descriptor_,
      PolygonList_Polygon::default_instance_,
      PolygonList_Polygon_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolygonList_Polygon, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolygonList_Polygon, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PolygonList_Polygon));
  PolygonList_Polygon_Vertex_descriptor_ = PolygonList_Polygon_descriptor_->nested_type(0);
  static const int PolygonList_Polygon_Vertex_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolygonList_Polygon_Vertex, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolygonList_Polygon_Vertex, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolygonList_Polygon_Vertex, z_),
  };
  PolygonList_Polygon_Vertex_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      PolygonList_Polygon_Vertex_descriptor_,
      PolygonList_Polygon_Vertex::default_instance_,
      PolygonList_Polygon_Vertex_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolygonList_Polygon_Vertex, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PolygonList_Polygon_Vertex, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(PolygonList_Polygon_Vertex));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_polygon_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PolygonList_descriptor_, &PolygonList::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PolygonList_Polygon_descriptor_, &PolygonList_Polygon::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    PolygonList_Polygon_Vertex_descriptor_, &PolygonList_Polygon_Vertex::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_polygon_2eproto() {
  delete PolygonList::default_instance_;
  delete PolygonList_reflection_;
  delete PolygonList_Polygon::default_instance_;
  delete PolygonList_Polygon_reflection_;
  delete PolygonList_Polygon_Vertex::default_instance_;
  delete PolygonList_Polygon_Vertex_reflection_;
}

void protobuf_AddDesc_polygon_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rpolygon.proto\022\004comm\"\244\001\n\013PolygonList\022+\n"
    "\010polygons\030\001 \003(\0132\031.comm.PolygonList.Polyg"
    "on\032h\n\007Polygon\0222\n\010vertices\030\001 \003(\0132 .comm.P"
    "olygonList.Polygon.Vertex\032)\n\006Vertex\022\t\n\001x"
    "\030\001 \002(\001\022\t\n\001y\030\002 \002(\001\022\t\n\001z\030\003 \002(\001", 188);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "polygon.proto", &protobuf_RegisterTypes);
  PolygonList::default_instance_ = new PolygonList();
  PolygonList_Polygon::default_instance_ = new PolygonList_Polygon();
  PolygonList_Polygon_Vertex::default_instance_ = new PolygonList_Polygon_Vertex();
  PolygonList::default_instance_->InitAsDefaultInstance();
  PolygonList_Polygon::default_instance_->InitAsDefaultInstance();
  PolygonList_Polygon_Vertex::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_polygon_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_polygon_2eproto {
  StaticDescriptorInitializer_polygon_2eproto() {
    protobuf_AddDesc_polygon_2eproto();
  }
} static_descriptor_initializer_polygon_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int PolygonList_Polygon_Vertex::kXFieldNumber;
const int PolygonList_Polygon_Vertex::kYFieldNumber;
const int PolygonList_Polygon_Vertex::kZFieldNumber;
#endif  // !_MSC_VER

PolygonList_Polygon_Vertex::PolygonList_Polygon_Vertex()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:comm.PolygonList.Polygon.Vertex)
}

void PolygonList_Polygon_Vertex::InitAsDefaultInstance() {
}

PolygonList_Polygon_Vertex::PolygonList_Polygon_Vertex(const PolygonList_Polygon_Vertex& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:comm.PolygonList.Polygon.Vertex)
}

void PolygonList_Polygon_Vertex::SharedCtor() {
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
  z_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PolygonList_Polygon_Vertex::~PolygonList_Polygon_Vertex() {
  // @@protoc_insertion_point(destructor:comm.PolygonList.Polygon.Vertex)
  SharedDtor();
}

void PolygonList_Polygon_Vertex::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PolygonList_Polygon_Vertex::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PolygonList_Polygon_Vertex::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PolygonList_Polygon_Vertex_descriptor_;
}

const PolygonList_Polygon_Vertex& PolygonList_Polygon_Vertex::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_polygon_2eproto();
  return *default_instance_;
}

PolygonList_Polygon_Vertex* PolygonList_Polygon_Vertex::default_instance_ = NULL;

PolygonList_Polygon_Vertex* PolygonList_Polygon_Vertex::New() const {
  return new PolygonList_Polygon_Vertex;
}

void PolygonList_Polygon_Vertex::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<PolygonList_Polygon_Vertex*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(x_, z_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PolygonList_Polygon_Vertex::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:comm.PolygonList.Polygon.Vertex)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required double x = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_y;
        break;
      }

      // required double y = 2;
      case 2: {
        if (tag == 17) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_z;
        break;
      }

      // required double z = 3;
      case 3: {
        if (tag == 25) {
         parse_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &z_)));
          set_has_z();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:comm.PolygonList.Polygon.Vertex)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:comm.PolygonList.Polygon.Vertex)
  return false;
#undef DO_
}

void PolygonList_Polygon_Vertex::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:comm.PolygonList.Polygon.Vertex)
  // required double x = 1;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->x(), output);
  }

  // required double y = 2;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->y(), output);
  }

  // required double z = 3;
  if (has_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->z(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:comm.PolygonList.Polygon.Vertex)
}

::google::protobuf::uint8* PolygonList_Polygon_Vertex::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:comm.PolygonList.Polygon.Vertex)
  // required double x = 1;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->x(), target);
  }

  // required double y = 2;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->y(), target);
  }

  // required double z = 3;
  if (has_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->z(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:comm.PolygonList.Polygon.Vertex)
  return target;
}

int PolygonList_Polygon_Vertex::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required double x = 1;
    if (has_x()) {
      total_size += 1 + 8;
    }

    // required double y = 2;
    if (has_y()) {
      total_size += 1 + 8;
    }

    // required double z = 3;
    if (has_z()) {
      total_size += 1 + 8;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PolygonList_Polygon_Vertex::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PolygonList_Polygon_Vertex* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PolygonList_Polygon_Vertex*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PolygonList_Polygon_Vertex::MergeFrom(const PolygonList_Polygon_Vertex& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_z()) {
      set_z(from.z());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PolygonList_Polygon_Vertex::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PolygonList_Polygon_Vertex::CopyFrom(const PolygonList_Polygon_Vertex& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PolygonList_Polygon_Vertex::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void PolygonList_Polygon_Vertex::Swap(PolygonList_Polygon_Vertex* other) {
  if (other != this) {
    std::swap(x_, other->x_);
    std::swap(y_, other->y_);
    std::swap(z_, other->z_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PolygonList_Polygon_Vertex::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PolygonList_Polygon_Vertex_descriptor_;
  metadata.reflection = PolygonList_Polygon_Vertex_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int PolygonList_Polygon::kVerticesFieldNumber;
#endif  // !_MSC_VER

PolygonList_Polygon::PolygonList_Polygon()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:comm.PolygonList.Polygon)
}

void PolygonList_Polygon::InitAsDefaultInstance() {
}

PolygonList_Polygon::PolygonList_Polygon(const PolygonList_Polygon& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:comm.PolygonList.Polygon)
}

void PolygonList_Polygon::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PolygonList_Polygon::~PolygonList_Polygon() {
  // @@protoc_insertion_point(destructor:comm.PolygonList.Polygon)
  SharedDtor();
}

void PolygonList_Polygon::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PolygonList_Polygon::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PolygonList_Polygon::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PolygonList_Polygon_descriptor_;
}

const PolygonList_Polygon& PolygonList_Polygon::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_polygon_2eproto();
  return *default_instance_;
}

PolygonList_Polygon* PolygonList_Polygon::default_instance_ = NULL;

PolygonList_Polygon* PolygonList_Polygon::New() const {
  return new PolygonList_Polygon;
}

void PolygonList_Polygon::Clear() {
  vertices_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PolygonList_Polygon::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:comm.PolygonList.Polygon)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .comm.PolygonList.Polygon.Vertex vertices = 1;
      case 1: {
        if (tag == 10) {
         parse_vertices:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_vertices()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_vertices;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:comm.PolygonList.Polygon)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:comm.PolygonList.Polygon)
  return false;
#undef DO_
}

void PolygonList_Polygon::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:comm.PolygonList.Polygon)
  // repeated .comm.PolygonList.Polygon.Vertex vertices = 1;
  for (int i = 0; i < this->vertices_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->vertices(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:comm.PolygonList.Polygon)
}

::google::protobuf::uint8* PolygonList_Polygon::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:comm.PolygonList.Polygon)
  // repeated .comm.PolygonList.Polygon.Vertex vertices = 1;
  for (int i = 0; i < this->vertices_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->vertices(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:comm.PolygonList.Polygon)
  return target;
}

int PolygonList_Polygon::ByteSize() const {
  int total_size = 0;

  // repeated .comm.PolygonList.Polygon.Vertex vertices = 1;
  total_size += 1 * this->vertices_size();
  for (int i = 0; i < this->vertices_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->vertices(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PolygonList_Polygon::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PolygonList_Polygon* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PolygonList_Polygon*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PolygonList_Polygon::MergeFrom(const PolygonList_Polygon& from) {
  GOOGLE_CHECK_NE(&from, this);
  vertices_.MergeFrom(from.vertices_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PolygonList_Polygon::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PolygonList_Polygon::CopyFrom(const PolygonList_Polygon& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PolygonList_Polygon::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->vertices())) return false;
  return true;
}

void PolygonList_Polygon::Swap(PolygonList_Polygon* other) {
  if (other != this) {
    vertices_.Swap(&other->vertices_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PolygonList_Polygon::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PolygonList_Polygon_descriptor_;
  metadata.reflection = PolygonList_Polygon_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int PolygonList::kPolygonsFieldNumber;
#endif  // !_MSC_VER

PolygonList::PolygonList()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:comm.PolygonList)
}

void PolygonList::InitAsDefaultInstance() {
}

PolygonList::PolygonList(const PolygonList& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:comm.PolygonList)
}

void PolygonList::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PolygonList::~PolygonList() {
  // @@protoc_insertion_point(destructor:comm.PolygonList)
  SharedDtor();
}

void PolygonList::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PolygonList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PolygonList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PolygonList_descriptor_;
}

const PolygonList& PolygonList::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_polygon_2eproto();
  return *default_instance_;
}

PolygonList* PolygonList::default_instance_ = NULL;

PolygonList* PolygonList::New() const {
  return new PolygonList;
}

void PolygonList::Clear() {
  polygons_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool PolygonList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:comm.PolygonList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .comm.PolygonList.Polygon polygons = 1;
      case 1: {
        if (tag == 10) {
         parse_polygons:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_polygons()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_polygons;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:comm.PolygonList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:comm.PolygonList)
  return false;
#undef DO_
}

void PolygonList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:comm.PolygonList)
  // repeated .comm.PolygonList.Polygon polygons = 1;
  for (int i = 0; i < this->polygons_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->polygons(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:comm.PolygonList)
}

::google::protobuf::uint8* PolygonList::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:comm.PolygonList)
  // repeated .comm.PolygonList.Polygon polygons = 1;
  for (int i = 0; i < this->polygons_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        1, this->polygons(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:comm.PolygonList)
  return target;
}

int PolygonList::ByteSize() const {
  int total_size = 0;

  // repeated .comm.PolygonList.Polygon polygons = 1;
  total_size += 1 * this->polygons_size();
  for (int i = 0; i < this->polygons_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->polygons(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PolygonList::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const PolygonList* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const PolygonList*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void PolygonList::MergeFrom(const PolygonList& from) {
  GOOGLE_CHECK_NE(&from, this);
  polygons_.MergeFrom(from.polygons_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void PolygonList::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PolygonList::CopyFrom(const PolygonList& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PolygonList::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->polygons())) return false;
  return true;
}

void PolygonList::Swap(PolygonList* other) {
  if (other != this) {
    polygons_.Swap(&other->polygons_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata PolygonList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PolygonList_descriptor_;
  metadata.reflection = PolygonList_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm

// @@protoc_insertion_point(global_scope)
