// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: polygon.proto

#ifndef PROTOBUF_polygon_2eproto__INCLUDED
#define PROTOBUF_polygon_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace comm {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_polygon_2eproto();
void protobuf_AssignDesc_polygon_2eproto();
void protobuf_ShutdownFile_polygon_2eproto();

class PolygonList;
class PolygonList_Polygon;
class PolygonList_Polygon_Vertex;

// ===================================================================

class PolygonList_Polygon_Vertex : public ::google::protobuf::Message {
 public:
  PolygonList_Polygon_Vertex();
  virtual ~PolygonList_Polygon_Vertex();

  PolygonList_Polygon_Vertex(const PolygonList_Polygon_Vertex& from);

  inline PolygonList_Polygon_Vertex& operator=(const PolygonList_Polygon_Vertex& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PolygonList_Polygon_Vertex& default_instance();

  void Swap(PolygonList_Polygon_Vertex* other);

  // implements Message ----------------------------------------------

  PolygonList_Polygon_Vertex* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PolygonList_Polygon_Vertex& from);
  void MergeFrom(const PolygonList_Polygon_Vertex& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double x = 1;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 1;
  inline double x() const;
  inline void set_x(double value);

  // required double y = 2;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 2;
  inline double y() const;
  inline void set_y(double value);

  // required double z = 3;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 3;
  inline double z() const;
  inline void set_z(double value);

  // @@protoc_insertion_point(class_scope:comm.PolygonList.Polygon.Vertex)
 private:
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double x_;
  double y_;
  double z_;
  friend void  protobuf_AddDesc_polygon_2eproto();
  friend void protobuf_AssignDesc_polygon_2eproto();
  friend void protobuf_ShutdownFile_polygon_2eproto();

  void InitAsDefaultInstance();
  static PolygonList_Polygon_Vertex* default_instance_;
};
// -------------------------------------------------------------------

class PolygonList_Polygon : public ::google::protobuf::Message {
 public:
  PolygonList_Polygon();
  virtual ~PolygonList_Polygon();

  PolygonList_Polygon(const PolygonList_Polygon& from);

  inline PolygonList_Polygon& operator=(const PolygonList_Polygon& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PolygonList_Polygon& default_instance();

  void Swap(PolygonList_Polygon* other);

  // implements Message ----------------------------------------------

  PolygonList_Polygon* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PolygonList_Polygon& from);
  void MergeFrom(const PolygonList_Polygon& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef PolygonList_Polygon_Vertex Vertex;

  // accessors -------------------------------------------------------

  // repeated .comm.PolygonList.Polygon.Vertex vertices = 1;
  inline int vertices_size() const;
  inline void clear_vertices();
  static const int kVerticesFieldNumber = 1;
  inline const ::comm::PolygonList_Polygon_Vertex& vertices(int index) const;
  inline ::comm::PolygonList_Polygon_Vertex* mutable_vertices(int index);
  inline ::comm::PolygonList_Polygon_Vertex* add_vertices();
  inline const ::google::protobuf::RepeatedPtrField< ::comm::PolygonList_Polygon_Vertex >&
      vertices() const;
  inline ::google::protobuf::RepeatedPtrField< ::comm::PolygonList_Polygon_Vertex >*
      mutable_vertices();

  // @@protoc_insertion_point(class_scope:comm.PolygonList.Polygon)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::comm::PolygonList_Polygon_Vertex > vertices_;
  friend void  protobuf_AddDesc_polygon_2eproto();
  friend void protobuf_AssignDesc_polygon_2eproto();
  friend void protobuf_ShutdownFile_polygon_2eproto();

  void InitAsDefaultInstance();
  static PolygonList_Polygon* default_instance_;
};
// -------------------------------------------------------------------

class PolygonList : public ::google::protobuf::Message {
 public:
  PolygonList();
  virtual ~PolygonList();

  PolygonList(const PolygonList& from);

  inline PolygonList& operator=(const PolygonList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PolygonList& default_instance();

  void Swap(PolygonList* other);

  // implements Message ----------------------------------------------

  PolygonList* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PolygonList& from);
  void MergeFrom(const PolygonList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef PolygonList_Polygon Polygon;

  // accessors -------------------------------------------------------

  // repeated .comm.PolygonList.Polygon polygons = 1;
  inline int polygons_size() const;
  inline void clear_polygons();
  static const int kPolygonsFieldNumber = 1;
  inline const ::comm::PolygonList_Polygon& polygons(int index) const;
  inline ::comm::PolygonList_Polygon* mutable_polygons(int index);
  inline ::comm::PolygonList_Polygon* add_polygons();
  inline const ::google::protobuf::RepeatedPtrField< ::comm::PolygonList_Polygon >&
      polygons() const;
  inline ::google::protobuf::RepeatedPtrField< ::comm::PolygonList_Polygon >*
      mutable_polygons();

  // @@protoc_insertion_point(class_scope:comm.PolygonList)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::comm::PolygonList_Polygon > polygons_;
  friend void  protobuf_AddDesc_polygon_2eproto();
  friend void protobuf_AssignDesc_polygon_2eproto();
  friend void protobuf_ShutdownFile_polygon_2eproto();

  void InitAsDefaultInstance();
  static PolygonList* default_instance_;
};
// ===================================================================


// ===================================================================

// PolygonList_Polygon_Vertex

// required double x = 1;
inline bool PolygonList_Polygon_Vertex::has_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PolygonList_Polygon_Vertex::set_has_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PolygonList_Polygon_Vertex::clear_has_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PolygonList_Polygon_Vertex::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double PolygonList_Polygon_Vertex::x() const {
  // @@protoc_insertion_point(field_get:comm.PolygonList.Polygon.Vertex.x)
  return x_;
}
inline void PolygonList_Polygon_Vertex::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:comm.PolygonList.Polygon.Vertex.x)
}

// required double y = 2;
inline bool PolygonList_Polygon_Vertex::has_y() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PolygonList_Polygon_Vertex::set_has_y() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PolygonList_Polygon_Vertex::clear_has_y() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PolygonList_Polygon_Vertex::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double PolygonList_Polygon_Vertex::y() const {
  // @@protoc_insertion_point(field_get:comm.PolygonList.Polygon.Vertex.y)
  return y_;
}
inline void PolygonList_Polygon_Vertex::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:comm.PolygonList.Polygon.Vertex.y)
}

// required double z = 3;
inline bool PolygonList_Polygon_Vertex::has_z() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PolygonList_Polygon_Vertex::set_has_z() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PolygonList_Polygon_Vertex::clear_has_z() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PolygonList_Polygon_Vertex::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double PolygonList_Polygon_Vertex::z() const {
  // @@protoc_insertion_point(field_get:comm.PolygonList.Polygon.Vertex.z)
  return z_;
}
inline void PolygonList_Polygon_Vertex::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:comm.PolygonList.Polygon.Vertex.z)
}

// -------------------------------------------------------------------

// PolygonList_Polygon

// repeated .comm.PolygonList.Polygon.Vertex vertices = 1;
inline int PolygonList_Polygon::vertices_size() const {
  return vertices_.size();
}
inline void PolygonList_Polygon::clear_vertices() {
  vertices_.Clear();
}
inline const ::comm::PolygonList_Polygon_Vertex& PolygonList_Polygon::vertices(int index) const {
  // @@protoc_insertion_point(field_get:comm.PolygonList.Polygon.vertices)
  return vertices_.Get(index);
}
inline ::comm::PolygonList_Polygon_Vertex* PolygonList_Polygon::mutable_vertices(int index) {
  // @@protoc_insertion_point(field_mutable:comm.PolygonList.Polygon.vertices)
  return vertices_.Mutable(index);
}
inline ::comm::PolygonList_Polygon_Vertex* PolygonList_Polygon::add_vertices() {
  // @@protoc_insertion_point(field_add:comm.PolygonList.Polygon.vertices)
  return vertices_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::comm::PolygonList_Polygon_Vertex >&
PolygonList_Polygon::vertices() const {
  // @@protoc_insertion_point(field_list:comm.PolygonList.Polygon.vertices)
  return vertices_;
}
inline ::google::protobuf::RepeatedPtrField< ::comm::PolygonList_Polygon_Vertex >*
PolygonList_Polygon::mutable_vertices() {
  // @@protoc_insertion_point(field_mutable_list:comm.PolygonList.Polygon.vertices)
  return &vertices_;
}

// -------------------------------------------------------------------

// PolygonList

// repeated .comm.PolygonList.Polygon polygons = 1;
inline int PolygonList::polygons_size() const {
  return polygons_.size();
}
inline void PolygonList::clear_polygons() {
  polygons_.Clear();
}
inline const ::comm::PolygonList_Polygon& PolygonList::polygons(int index) const {
  // @@protoc_insertion_point(field_get:comm.PolygonList.polygons)
  return polygons_.Get(index);
}
inline ::comm::PolygonList_Polygon* PolygonList::mutable_polygons(int index) {
  // @@protoc_insertion_point(field_mutable:comm.PolygonList.polygons)
  return polygons_.Mutable(index);
}
inline ::comm::PolygonList_Polygon* PolygonList::add_polygons() {
  // @@protoc_insertion_point(field_add:comm.PolygonList.polygons)
  return polygons_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::comm::PolygonList_Polygon >&
PolygonList::polygons() const {
  // @@protoc_insertion_point(field_list:comm.PolygonList.polygons)
  return polygons_;
}
inline ::google::protobuf::RepeatedPtrField< ::comm::PolygonList_Polygon >*
PolygonList::mutable_polygons() {
  // @@protoc_insertion_point(field_mutable_list:comm.PolygonList.polygons)
  return &polygons_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_polygon_2eproto__INCLUDED
