// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: swarm.proto

#ifndef PROTOBUF_swarm_2eproto__INCLUDED
#define PROTOBUF_swarm_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace comm {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_swarm_2eproto();
void protobuf_AssignDesc_swarm_2eproto();
void protobuf_ShutdownFile_swarm_2eproto();

class Swarm;
class Swarm_Agent;

enum Swarm_Agent_Mode {
  Swarm_Agent_Mode_SURROUND = 1,
  Swarm_Agent_Mode_TRAVEL_LEAD = 2,
  Swarm_Agent_Mode_TRAVEL_FOLLOW = 3
};
bool Swarm_Agent_Mode_IsValid(int value);
const Swarm_Agent_Mode Swarm_Agent_Mode_Mode_MIN = Swarm_Agent_Mode_SURROUND;
const Swarm_Agent_Mode Swarm_Agent_Mode_Mode_MAX = Swarm_Agent_Mode_TRAVEL_FOLLOW;
const int Swarm_Agent_Mode_Mode_ARRAYSIZE = Swarm_Agent_Mode_Mode_MAX + 1;

const ::google::protobuf::EnumDescriptor* Swarm_Agent_Mode_descriptor();
inline const ::std::string& Swarm_Agent_Mode_Name(Swarm_Agent_Mode value) {
  return ::google::protobuf::internal::NameOfEnum(
    Swarm_Agent_Mode_descriptor(), value);
}
inline bool Swarm_Agent_Mode_Parse(
    const ::std::string& name, Swarm_Agent_Mode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Swarm_Agent_Mode>(
    Swarm_Agent_Mode_descriptor(), name, value);
}
// ===================================================================

class Swarm_Agent : public ::google::protobuf::Message {
 public:
  Swarm_Agent();
  virtual ~Swarm_Agent();

  Swarm_Agent(const Swarm_Agent& from);

  inline Swarm_Agent& operator=(const Swarm_Agent& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Swarm_Agent& default_instance();

  void Swap(Swarm_Agent* other);

  // implements Message ----------------------------------------------

  Swarm_Agent* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Swarm_Agent& from);
  void MergeFrom(const Swarm_Agent& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Swarm_Agent_Mode Mode;
  static const Mode SURROUND = Swarm_Agent_Mode_SURROUND;
  static const Mode TRAVEL_LEAD = Swarm_Agent_Mode_TRAVEL_LEAD;
  static const Mode TRAVEL_FOLLOW = Swarm_Agent_Mode_TRAVEL_FOLLOW;
  static inline bool Mode_IsValid(int value) {
    return Swarm_Agent_Mode_IsValid(value);
  }
  static const Mode Mode_MIN =
    Swarm_Agent_Mode_Mode_MIN;
  static const Mode Mode_MAX =
    Swarm_Agent_Mode_Mode_MAX;
  static const int Mode_ARRAYSIZE =
    Swarm_Agent_Mode_Mode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Mode_descriptor() {
    return Swarm_Agent_Mode_descriptor();
  }
  static inline const ::std::string& Mode_Name(Mode value) {
    return Swarm_Agent_Mode_Name(value);
  }
  static inline bool Mode_Parse(const ::std::string& name,
      Mode* value) {
    return Swarm_Agent_Mode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required double x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline double x() const;
  inline void set_x(double value);

  // required double y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline double y() const;
  inline void set_y(double value);

  // required double z = 4;
  inline bool has_z() const;
  inline void clear_z();
  static const int kZFieldNumber = 4;
  inline double z() const;
  inline void set_z(double value);

  // required .comm.Swarm.Agent.Mode mode = 5;
  inline bool has_mode() const;
  inline void clear_mode();
  static const int kModeFieldNumber = 5;
  inline ::comm::Swarm_Agent_Mode mode() const;
  inline void set_mode(::comm::Swarm_Agent_Mode value);

  // repeated int32 Neighbours = 6;
  inline int neighbours_size() const;
  inline void clear_neighbours();
  static const int kNeighboursFieldNumber = 6;
  inline ::google::protobuf::int32 neighbours(int index) const;
  inline void set_neighbours(int index, ::google::protobuf::int32 value);
  inline void add_neighbours(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      neighbours() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_neighbours();

  // required double forceX = 7;
  inline bool has_forcex() const;
  inline void clear_forcex();
  static const int kForceXFieldNumber = 7;
  inline double forcex() const;
  inline void set_forcex(double value);

  // required double forceY = 8;
  inline bool has_forcey() const;
  inline void clear_forcey();
  static const int kForceYFieldNumber = 8;
  inline double forcey() const;
  inline void set_forcey(double value);

  // required double forceZ = 9;
  inline bool has_forcez() const;
  inline void clear_forcez();
  static const int kForceZFieldNumber = 9;
  inline double forcez() const;
  inline void set_forcez(double value);

  // @@protoc_insertion_point(class_scope:comm.Swarm.Agent)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  inline void set_has_z();
  inline void clear_has_z();
  inline void set_has_mode();
  inline void clear_has_mode();
  inline void set_has_forcex();
  inline void clear_has_forcex();
  inline void set_has_forcey();
  inline void clear_has_forcey();
  inline void set_has_forcez();
  inline void clear_has_forcez();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double x_;
  double y_;
  ::google::protobuf::int32 id_;
  int mode_;
  double z_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > neighbours_;
  double forcex_;
  double forcey_;
  double forcez_;
  friend void  protobuf_AddDesc_swarm_2eproto();
  friend void protobuf_AssignDesc_swarm_2eproto();
  friend void protobuf_ShutdownFile_swarm_2eproto();

  void InitAsDefaultInstance();
  static Swarm_Agent* default_instance_;
};
// -------------------------------------------------------------------

class Swarm : public ::google::protobuf::Message {
 public:
  Swarm();
  virtual ~Swarm();

  Swarm(const Swarm& from);

  inline Swarm& operator=(const Swarm& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Swarm& default_instance();

  void Swap(Swarm* other);

  // implements Message ----------------------------------------------

  Swarm* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Swarm& from);
  void MergeFrom(const Swarm& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef Swarm_Agent Agent;

  // accessors -------------------------------------------------------

  // repeated int32 cycle = 1;
  inline int cycle_size() const;
  inline void clear_cycle();
  static const int kCycleFieldNumber = 1;
  inline ::google::protobuf::int32 cycle(int index) const;
  inline void set_cycle(int index, ::google::protobuf::int32 value);
  inline void add_cycle(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      cycle() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_cycle();

  // repeated .comm.Swarm.Agent agents = 2;
  inline int agents_size() const;
  inline void clear_agents();
  static const int kAgentsFieldNumber = 2;
  inline const ::comm::Swarm_Agent& agents(int index) const;
  inline ::comm::Swarm_Agent* mutable_agents(int index);
  inline ::comm::Swarm_Agent* add_agents();
  inline const ::google::protobuf::RepeatedPtrField< ::comm::Swarm_Agent >&
      agents() const;
  inline ::google::protobuf::RepeatedPtrField< ::comm::Swarm_Agent >*
      mutable_agents();

  // required double radius = 3;
  inline bool has_radius() const;
  inline void clear_radius();
  static const int kRadiusFieldNumber = 3;
  inline double radius() const;
  inline void set_radius(double value);

  // @@protoc_insertion_point(class_scope:comm.Swarm)
 private:
  inline void set_has_radius();
  inline void clear_has_radius();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > cycle_;
  ::google::protobuf::RepeatedPtrField< ::comm::Swarm_Agent > agents_;
  double radius_;
  friend void  protobuf_AddDesc_swarm_2eproto();
  friend void protobuf_AssignDesc_swarm_2eproto();
  friend void protobuf_ShutdownFile_swarm_2eproto();

  void InitAsDefaultInstance();
  static Swarm* default_instance_;
};
// ===================================================================


// ===================================================================

// Swarm_Agent

// required int32 id = 1;
inline bool Swarm_Agent::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Swarm_Agent::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Swarm_Agent::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Swarm_Agent::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Swarm_Agent::id() const {
  // @@protoc_insertion_point(field_get:comm.Swarm.Agent.id)
  return id_;
}
inline void Swarm_Agent::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:comm.Swarm.Agent.id)
}

// required double x = 2;
inline bool Swarm_Agent::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Swarm_Agent::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Swarm_Agent::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Swarm_Agent::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double Swarm_Agent::x() const {
  // @@protoc_insertion_point(field_get:comm.Swarm.Agent.x)
  return x_;
}
inline void Swarm_Agent::set_x(double value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:comm.Swarm.Agent.x)
}

// required double y = 3;
inline bool Swarm_Agent::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Swarm_Agent::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Swarm_Agent::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Swarm_Agent::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double Swarm_Agent::y() const {
  // @@protoc_insertion_point(field_get:comm.Swarm.Agent.y)
  return y_;
}
inline void Swarm_Agent::set_y(double value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:comm.Swarm.Agent.y)
}

// required double z = 4;
inline bool Swarm_Agent::has_z() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Swarm_Agent::set_has_z() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Swarm_Agent::clear_has_z() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Swarm_Agent::clear_z() {
  z_ = 0;
  clear_has_z();
}
inline double Swarm_Agent::z() const {
  // @@protoc_insertion_point(field_get:comm.Swarm.Agent.z)
  return z_;
}
inline void Swarm_Agent::set_z(double value) {
  set_has_z();
  z_ = value;
  // @@protoc_insertion_point(field_set:comm.Swarm.Agent.z)
}

// required .comm.Swarm.Agent.Mode mode = 5;
inline bool Swarm_Agent::has_mode() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Swarm_Agent::set_has_mode() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Swarm_Agent::clear_has_mode() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Swarm_Agent::clear_mode() {
  mode_ = 1;
  clear_has_mode();
}
inline ::comm::Swarm_Agent_Mode Swarm_Agent::mode() const {
  // @@protoc_insertion_point(field_get:comm.Swarm.Agent.mode)
  return static_cast< ::comm::Swarm_Agent_Mode >(mode_);
}
inline void Swarm_Agent::set_mode(::comm::Swarm_Agent_Mode value) {
  assert(::comm::Swarm_Agent_Mode_IsValid(value));
  set_has_mode();
  mode_ = value;
  // @@protoc_insertion_point(field_set:comm.Swarm.Agent.mode)
}

// repeated int32 Neighbours = 6;
inline int Swarm_Agent::neighbours_size() const {
  return neighbours_.size();
}
inline void Swarm_Agent::clear_neighbours() {
  neighbours_.Clear();
}
inline ::google::protobuf::int32 Swarm_Agent::neighbours(int index) const {
  // @@protoc_insertion_point(field_get:comm.Swarm.Agent.Neighbours)
  return neighbours_.Get(index);
}
inline void Swarm_Agent::set_neighbours(int index, ::google::protobuf::int32 value) {
  neighbours_.Set(index, value);
  // @@protoc_insertion_point(field_set:comm.Swarm.Agent.Neighbours)
}
inline void Swarm_Agent::add_neighbours(::google::protobuf::int32 value) {
  neighbours_.Add(value);
  // @@protoc_insertion_point(field_add:comm.Swarm.Agent.Neighbours)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Swarm_Agent::neighbours() const {
  // @@protoc_insertion_point(field_list:comm.Swarm.Agent.Neighbours)
  return neighbours_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Swarm_Agent::mutable_neighbours() {
  // @@protoc_insertion_point(field_mutable_list:comm.Swarm.Agent.Neighbours)
  return &neighbours_;
}

// required double forceX = 7;
inline bool Swarm_Agent::has_forcex() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Swarm_Agent::set_has_forcex() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Swarm_Agent::clear_has_forcex() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Swarm_Agent::clear_forcex() {
  forcex_ = 0;
  clear_has_forcex();
}
inline double Swarm_Agent::forcex() const {
  // @@protoc_insertion_point(field_get:comm.Swarm.Agent.forceX)
  return forcex_;
}
inline void Swarm_Agent::set_forcex(double value) {
  set_has_forcex();
  forcex_ = value;
  // @@protoc_insertion_point(field_set:comm.Swarm.Agent.forceX)
}

// required double forceY = 8;
inline bool Swarm_Agent::has_forcey() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Swarm_Agent::set_has_forcey() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Swarm_Agent::clear_has_forcey() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Swarm_Agent::clear_forcey() {
  forcey_ = 0;
  clear_has_forcey();
}
inline double Swarm_Agent::forcey() const {
  // @@protoc_insertion_point(field_get:comm.Swarm.Agent.forceY)
  return forcey_;
}
inline void Swarm_Agent::set_forcey(double value) {
  set_has_forcey();
  forcey_ = value;
  // @@protoc_insertion_point(field_set:comm.Swarm.Agent.forceY)
}

// required double forceZ = 9;
inline bool Swarm_Agent::has_forcez() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void Swarm_Agent::set_has_forcez() {
  _has_bits_[0] |= 0x00000100u;
}
inline void Swarm_Agent::clear_has_forcez() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void Swarm_Agent::clear_forcez() {
  forcez_ = 0;
  clear_has_forcez();
}
inline double Swarm_Agent::forcez() const {
  // @@protoc_insertion_point(field_get:comm.Swarm.Agent.forceZ)
  return forcez_;
}
inline void Swarm_Agent::set_forcez(double value) {
  set_has_forcez();
  forcez_ = value;
  // @@protoc_insertion_point(field_set:comm.Swarm.Agent.forceZ)
}

// -------------------------------------------------------------------

// Swarm

// repeated int32 cycle = 1;
inline int Swarm::cycle_size() const {
  return cycle_.size();
}
inline void Swarm::clear_cycle() {
  cycle_.Clear();
}
inline ::google::protobuf::int32 Swarm::cycle(int index) const {
  // @@protoc_insertion_point(field_get:comm.Swarm.cycle)
  return cycle_.Get(index);
}
inline void Swarm::set_cycle(int index, ::google::protobuf::int32 value) {
  cycle_.Set(index, value);
  // @@protoc_insertion_point(field_set:comm.Swarm.cycle)
}
inline void Swarm::add_cycle(::google::protobuf::int32 value) {
  cycle_.Add(value);
  // @@protoc_insertion_point(field_add:comm.Swarm.cycle)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
Swarm::cycle() const {
  // @@protoc_insertion_point(field_list:comm.Swarm.cycle)
  return cycle_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
Swarm::mutable_cycle() {
  // @@protoc_insertion_point(field_mutable_list:comm.Swarm.cycle)
  return &cycle_;
}

// repeated .comm.Swarm.Agent agents = 2;
inline int Swarm::agents_size() const {
  return agents_.size();
}
inline void Swarm::clear_agents() {
  agents_.Clear();
}
inline const ::comm::Swarm_Agent& Swarm::agents(int index) const {
  // @@protoc_insertion_point(field_get:comm.Swarm.agents)
  return agents_.Get(index);
}
inline ::comm::Swarm_Agent* Swarm::mutable_agents(int index) {
  // @@protoc_insertion_point(field_mutable:comm.Swarm.agents)
  return agents_.Mutable(index);
}
inline ::comm::Swarm_Agent* Swarm::add_agents() {
  // @@protoc_insertion_point(field_add:comm.Swarm.agents)
  return agents_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::comm::Swarm_Agent >&
Swarm::agents() const {
  // @@protoc_insertion_point(field_list:comm.Swarm.agents)
  return agents_;
}
inline ::google::protobuf::RepeatedPtrField< ::comm::Swarm_Agent >*
Swarm::mutable_agents() {
  // @@protoc_insertion_point(field_mutable_list:comm.Swarm.agents)
  return &agents_;
}

// required double radius = 3;
inline bool Swarm::has_radius() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Swarm::set_has_radius() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Swarm::clear_has_radius() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Swarm::clear_radius() {
  radius_ = 0;
  clear_has_radius();
}
inline double Swarm::radius() const {
  // @@protoc_insertion_point(field_get:comm.Swarm.radius)
  return radius_;
}
inline void Swarm::set_radius(double value) {
  set_has_radius();
  radius_ = value;
  // @@protoc_insertion_point(field_set:comm.Swarm.radius)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::comm::Swarm_Agent_Mode> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::comm::Swarm_Agent_Mode>() {
  return ::comm::Swarm_Agent_Mode_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_swarm_2eproto__INCLUDED
