// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: swarm.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "swarm.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace comm {

namespace {

const ::google::protobuf::Descriptor* Swarm_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Swarm_reflection_ = NULL;
const ::google::protobuf::Descriptor* Swarm_Agent_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Swarm_Agent_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Swarm_Agent_Mode_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_swarm_2eproto() {
  protobuf_AddDesc_swarm_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "swarm.proto");
  GOOGLE_CHECK(file != NULL);
  Swarm_descriptor_ = file->message_type(0);
  static const int Swarm_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm, cycle_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm, agents_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm, radius_),
  };
  Swarm_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Swarm_descriptor_,
      Swarm::default_instance_,
      Swarm_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Swarm));
  Swarm_Agent_descriptor_ = Swarm_descriptor_->nested_type(0);
  static const int Swarm_Agent_offsets_[9] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm_Agent, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm_Agent, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm_Agent, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm_Agent, z_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm_Agent, mode_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm_Agent, neighbours_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm_Agent, forcex_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm_Agent, forcey_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm_Agent, forcez_),
  };
  Swarm_Agent_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Swarm_Agent_descriptor_,
      Swarm_Agent::default_instance_,
      Swarm_Agent_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm_Agent, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Swarm_Agent, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Swarm_Agent));
  Swarm_Agent_Mode_descriptor_ = Swarm_Agent_descriptor_->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_swarm_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Swarm_descriptor_, &Swarm::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Swarm_Agent_descriptor_, &Swarm_Agent::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_swarm_2eproto() {
  delete Swarm::default_instance_;
  delete Swarm_reflection_;
  delete Swarm_Agent::default_instance_;
  delete Swarm_Agent_reflection_;
}

void protobuf_AddDesc_swarm_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013swarm.proto\022\004comm\"\244\002\n\005Swarm\022\r\n\005cycle\030\001"
    " \003(\005\022!\n\006agents\030\002 \003(\0132\021.comm.Swarm.Agent\022"
    "\016\n\006radius\030\003 \002(\001\032\330\001\n\005Agent\022\n\n\002id\030\001 \002(\005\022\t\n"
    "\001x\030\002 \002(\001\022\t\n\001y\030\003 \002(\001\022\t\n\001z\030\004 \002(\001\022$\n\004mode\030\005"
    " \002(\0162\026.comm.Swarm.Agent.Mode\022\022\n\nNeighbou"
    "rs\030\006 \003(\005\022\016\n\006forceX\030\007 \002(\001\022\016\n\006forceY\030\010 \002(\001"
    "\022\016\n\006forceZ\030\t \002(\001\"8\n\004Mode\022\014\n\010SURROUND\020\001\022\017"
    "\n\013TRAVEL_LEAD\020\002\022\021\n\rTRAVEL_FOLLOW\020\003", 314);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "swarm.proto", &protobuf_RegisterTypes);
  Swarm::default_instance_ = new Swarm();
  Swarm_Agent::default_instance_ = new Swarm_Agent();
  Swarm::default_instance_->InitAsDefaultInstance();
  Swarm_Agent::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_swarm_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_swarm_2eproto {
  StaticDescriptorInitializer_swarm_2eproto() {
    protobuf_AddDesc_swarm_2eproto();
  }
} static_descriptor_initializer_swarm_2eproto_;

// ===================================================================

const ::google::protobuf::EnumDescriptor* Swarm_Agent_Mode_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Swarm_Agent_Mode_descriptor_;
}
bool Swarm_Agent_Mode_IsValid(int value) {
  switch(value) {
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#ifndef _MSC_VER
const Swarm_Agent_Mode Swarm_Agent::SURROUND;
const Swarm_Agent_Mode Swarm_Agent::TRAVEL_LEAD;
const Swarm_Agent_Mode Swarm_Agent::TRAVEL_FOLLOW;
const Swarm_Agent_Mode Swarm_Agent::Mode_MIN;
const Swarm_Agent_Mode Swarm_Agent::Mode_MAX;
const int Swarm_Agent::Mode_ARRAYSIZE;
#endif  // _MSC_VER
#ifndef _MSC_VER
const int Swarm_Agent::kIdFieldNumber;
const int Swarm_Agent::kXFieldNumber;
const int Swarm_Agent::kYFieldNumber;
const int Swarm_Agent::kZFieldNumber;
const int Swarm_Agent::kModeFieldNumber;
const int Swarm_Agent::kNeighboursFieldNumber;
const int Swarm_Agent::kForceXFieldNumber;
const int Swarm_Agent::kForceYFieldNumber;
const int Swarm_Agent::kForceZFieldNumber;
#endif  // !_MSC_VER

Swarm_Agent::Swarm_Agent()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:comm.Swarm.Agent)
}

void Swarm_Agent::InitAsDefaultInstance() {
}

Swarm_Agent::Swarm_Agent(const Swarm_Agent& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:comm.Swarm.Agent)
}

void Swarm_Agent::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0;
  x_ = 0;
  y_ = 0;
  z_ = 0;
  mode_ = 1;
  forcex_ = 0;
  forcey_ = 0;
  forcez_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Swarm_Agent::~Swarm_Agent() {
  // @@protoc_insertion_point(destructor:comm.Swarm.Agent)
  SharedDtor();
}

void Swarm_Agent::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Swarm_Agent::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Swarm_Agent::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Swarm_Agent_descriptor_;
}

const Swarm_Agent& Swarm_Agent::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_swarm_2eproto();
  return *default_instance_;
}

Swarm_Agent* Swarm_Agent::default_instance_ = NULL;

Swarm_Agent* Swarm_Agent::New() const {
  return new Swarm_Agent;
}

void Swarm_Agent::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<Swarm_Agent*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 223) {
    ZR_(x_, id_);
    ZR_(forcex_, forcey_);
    z_ = 0;
    mode_ = 1;
  }
  forcez_ = 0;

#undef OFFSET_OF_FIELD_
#undef ZR_

  neighbours_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Swarm_Agent::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:comm.Swarm.Agent)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_x;
        break;
      }

      // required double x = 2;
      case 2: {
        if (tag == 17) {
         parse_x:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &x_)));
          set_has_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(25)) goto parse_y;
        break;
      }

      // required double y = 3;
      case 3: {
        if (tag == 25) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &y_)));
          set_has_y();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(33)) goto parse_z;
        break;
      }

      // required double z = 4;
      case 4: {
        if (tag == 33) {
         parse_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &z_)));
          set_has_z();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_mode;
        break;
      }

      // required .comm.Swarm.Agent.Mode mode = 5;
      case 5: {
        if (tag == 40) {
         parse_mode:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::comm::Swarm_Agent_Mode_IsValid(value)) {
            set_mode(static_cast< ::comm::Swarm_Agent_Mode >(value));
          } else {
            mutable_unknown_fields()->AddVarint(5, value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_Neighbours;
        break;
      }

      // repeated int32 Neighbours = 6;
      case 6: {
        if (tag == 48) {
         parse_Neighbours:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 48, input, this->mutable_neighbours())));
        } else if (tag == 50) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_neighbours())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_Neighbours;
        if (input->ExpectTag(57)) goto parse_forceX;
        break;
      }

      // required double forceX = 7;
      case 7: {
        if (tag == 57) {
         parse_forceX:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &forcex_)));
          set_has_forcex();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(65)) goto parse_forceY;
        break;
      }

      // required double forceY = 8;
      case 8: {
        if (tag == 65) {
         parse_forceY:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &forcey_)));
          set_has_forcey();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(73)) goto parse_forceZ;
        break;
      }

      // required double forceZ = 9;
      case 9: {
        if (tag == 73) {
         parse_forceZ:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &forcez_)));
          set_has_forcez();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:comm.Swarm.Agent)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:comm.Swarm.Agent)
  return false;
#undef DO_
}

void Swarm_Agent::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:comm.Swarm.Agent)
  // required int32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // required double x = 2;
  if (has_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->x(), output);
  }

  // required double y = 3;
  if (has_y()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->y(), output);
  }

  // required double z = 4;
  if (has_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(4, this->z(), output);
  }

  // required .comm.Swarm.Agent.Mode mode = 5;
  if (has_mode()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      5, this->mode(), output);
  }

  // repeated int32 Neighbours = 6;
  for (int i = 0; i < this->neighbours_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      6, this->neighbours(i), output);
  }

  // required double forceX = 7;
  if (has_forcex()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(7, this->forcex(), output);
  }

  // required double forceY = 8;
  if (has_forcey()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(8, this->forcey(), output);
  }

  // required double forceZ = 9;
  if (has_forcez()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->forcez(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:comm.Swarm.Agent)
}

::google::protobuf::uint8* Swarm_Agent::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:comm.Swarm.Agent)
  // required int32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // required double x = 2;
  if (has_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->x(), target);
  }

  // required double y = 3;
  if (has_y()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->y(), target);
  }

  // required double z = 4;
  if (has_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(4, this->z(), target);
  }

  // required .comm.Swarm.Agent.Mode mode = 5;
  if (has_mode()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      5, this->mode(), target);
  }

  // repeated int32 Neighbours = 6;
  for (int i = 0; i < this->neighbours_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(6, this->neighbours(i), target);
  }

  // required double forceX = 7;
  if (has_forcex()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(7, this->forcex(), target);
  }

  // required double forceY = 8;
  if (has_forcey()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(8, this->forcey(), target);
  }

  // required double forceZ = 9;
  if (has_forcez()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->forcez(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:comm.Swarm.Agent)
  return target;
}

int Swarm_Agent::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 id = 1;
    if (has_id()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->id());
    }

    // required double x = 2;
    if (has_x()) {
      total_size += 1 + 8;
    }

    // required double y = 3;
    if (has_y()) {
      total_size += 1 + 8;
    }

    // required double z = 4;
    if (has_z()) {
      total_size += 1 + 8;
    }

    // required .comm.Swarm.Agent.Mode mode = 5;
    if (has_mode()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::EnumSize(this->mode());
    }

    // required double forceX = 7;
    if (has_forcex()) {
      total_size += 1 + 8;
    }

    // required double forceY = 8;
    if (has_forcey()) {
      total_size += 1 + 8;
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // required double forceZ = 9;
    if (has_forcez()) {
      total_size += 1 + 8;
    }

  }
  // repeated int32 Neighbours = 6;
  {
    int data_size = 0;
    for (int i = 0; i < this->neighbours_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->neighbours(i));
    }
    total_size += 1 * this->neighbours_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Swarm_Agent::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Swarm_Agent* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Swarm_Agent*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Swarm_Agent::MergeFrom(const Swarm_Agent& from) {
  GOOGLE_CHECK_NE(&from, this);
  neighbours_.MergeFrom(from.neighbours_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_x()) {
      set_x(from.x());
    }
    if (from.has_y()) {
      set_y(from.y());
    }
    if (from.has_z()) {
      set_z(from.z());
    }
    if (from.has_mode()) {
      set_mode(from.mode());
    }
    if (from.has_forcex()) {
      set_forcex(from.forcex());
    }
    if (from.has_forcey()) {
      set_forcey(from.forcey());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_forcez()) {
      set_forcez(from.forcez());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Swarm_Agent::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Swarm_Agent::CopyFrom(const Swarm_Agent& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Swarm_Agent::IsInitialized() const {
  if ((_has_bits_[0] & 0x000001df) != 0x000001df) return false;

  return true;
}

void Swarm_Agent::Swap(Swarm_Agent* other) {
  if (other != this) {
    std::swap(id_, other->id_);
    std::swap(x_, other->x_);
    std::swap(y_, other->y_);
    std::swap(z_, other->z_);
    std::swap(mode_, other->mode_);
    neighbours_.Swap(&other->neighbours_);
    std::swap(forcex_, other->forcex_);
    std::swap(forcey_, other->forcey_);
    std::swap(forcez_, other->forcez_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Swarm_Agent::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Swarm_Agent_descriptor_;
  metadata.reflection = Swarm_Agent_reflection_;
  return metadata;
}


// -------------------------------------------------------------------

#ifndef _MSC_VER
const int Swarm::kCycleFieldNumber;
const int Swarm::kAgentsFieldNumber;
const int Swarm::kRadiusFieldNumber;
#endif  // !_MSC_VER

Swarm::Swarm()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:comm.Swarm)
}

void Swarm::InitAsDefaultInstance() {
}

Swarm::Swarm(const Swarm& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:comm.Swarm)
}

void Swarm::SharedCtor() {
  _cached_size_ = 0;
  radius_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Swarm::~Swarm() {
  // @@protoc_insertion_point(destructor:comm.Swarm)
  SharedDtor();
}

void Swarm::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Swarm::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Swarm::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Swarm_descriptor_;
}

const Swarm& Swarm::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_swarm_2eproto();
  return *default_instance_;
}

Swarm* Swarm::default_instance_ = NULL;

Swarm* Swarm::New() const {
  return new Swarm;
}

void Swarm::Clear() {
  radius_ = 0;
  cycle_.Clear();
  agents_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Swarm::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:comm.Swarm)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 cycle = 1;
      case 1: {
        if (tag == 8) {
         parse_cycle:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 8, input, this->mutable_cycle())));
        } else if (tag == 10) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_cycle())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(8)) goto parse_cycle;
        if (input->ExpectTag(18)) goto parse_agents;
        break;
      }

      // repeated .comm.Swarm.Agent agents = 2;
      case 2: {
        if (tag == 18) {
         parse_agents:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_agents()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_agents;
        if (input->ExpectTag(25)) goto parse_radius;
        break;
      }

      // required double radius = 3;
      case 3: {
        if (tag == 25) {
         parse_radius:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &radius_)));
          set_has_radius();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:comm.Swarm)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:comm.Swarm)
  return false;
#undef DO_
}

void Swarm::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:comm.Swarm)
  // repeated int32 cycle = 1;
  for (int i = 0; i < this->cycle_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      1, this->cycle(i), output);
  }

  // repeated .comm.Swarm.Agent agents = 2;
  for (int i = 0; i < this->agents_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->agents(i), output);
  }

  // required double radius = 3;
  if (has_radius()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(3, this->radius(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:comm.Swarm)
}

::google::protobuf::uint8* Swarm::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:comm.Swarm)
  // repeated int32 cycle = 1;
  for (int i = 0; i < this->cycle_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(1, this->cycle(i), target);
  }

  // repeated .comm.Swarm.Agent agents = 2;
  for (int i = 0; i < this->agents_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        2, this->agents(i), target);
  }

  // required double radius = 3;
  if (has_radius()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(3, this->radius(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:comm.Swarm)
  return target;
}

int Swarm::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[2 / 32] & (0xffu << (2 % 32))) {
    // required double radius = 3;
    if (has_radius()) {
      total_size += 1 + 8;
    }

  }
  // repeated int32 cycle = 1;
  {
    int data_size = 0;
    for (int i = 0; i < this->cycle_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->cycle(i));
    }
    total_size += 1 * this->cycle_size() + data_size;
  }

  // repeated .comm.Swarm.Agent agents = 2;
  total_size += 1 * this->agents_size();
  for (int i = 0; i < this->agents_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->agents(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Swarm::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Swarm* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Swarm*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Swarm::MergeFrom(const Swarm& from) {
  GOOGLE_CHECK_NE(&from, this);
  cycle_.MergeFrom(from.cycle_);
  agents_.MergeFrom(from.agents_);
  if (from._has_bits_[2 / 32] & (0xffu << (2 % 32))) {
    if (from.has_radius()) {
      set_radius(from.radius());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Swarm::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Swarm::CopyFrom(const Swarm& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Swarm::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000004) != 0x00000004) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->agents())) return false;
  return true;
}

void Swarm::Swap(Swarm* other) {
  if (other != this) {
    cycle_.Swap(&other->cycle_);
    agents_.Swap(&other->agents_);
    std::swap(radius_, other->radius_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Swarm::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Swarm_descriptor_;
  metadata.reflection = Swarm_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace comm

// @@protoc_insertion_point(global_scope)
